PUT http://localhost:5000/updateuser
Content-Type: application/json

{
    "email": "JIMBOB@yahoo.com",
    "resumes": {"name": "fullstack", "text": "this is some resume text", "resume":{"name":"dog", "text":"yes"}}
}