PUT http://localhost:5000/updateuser
Content-Type: application/json

{
    "email": "JIMBOB@yahoo.com",
    "skills": [
        {"name": "JavaScript", "keywords": ["yellow","Red", "Green"], "description": "Once I ate a hotdog"},
        {"name": "MochaScript", "keywords": ["yellow","Red", "Green"], "description": "Once I ate a hotdog"},
        {"name": "PokaScript", "keywords": ["yellow","Red", "Green"], "description": "Once I ate a hotdog"}
    ],
    "dog": "yes"
}