POST http://localhost:5000/verify
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJyZXR0YnVobGVyQHlhaG9vLmNvbSIsImlhdCI6MTY4MzMxNTQ4NCwiZXhwIjoxNjgzMzE5MDg0fQ.30n5qbh0DUrCQmAixBcjkV_FIw018UUxdVO9T4o2WCY"
}


